### ISSUE TITLE
LDAP password in source

### ISSUE THREAD

**Issue by ldionmarcil** [ClubCedille/cedille-ldap#4]
See https://github.com/ClubCedille/cedille-ldap/blob/7709e4846993fd7db7945c2acd6f7a769a80fae6/docker-compose-variables.yaml

You should find a safer way to handle passwords. Probably should change passwords too...

**Comment by mikefaille** [comment]
Its not your password. We use this password from your fork man. Use "git blame" to know that.

**Comment by mikefaille** [comment]
@ldionmarcil  Who spot this first my friend ?

**Comment by mikefaille** [comment]
@ldionmarcil It came from this example :  
https://github.com/osixia/docker-openldap#create-new-ldap-server

**Comment by mikefaille** [comment]
In this case, this is a quickstart for newcomer. But, to quicklaunch an instance, you can inject hashed password using slappasswd got from secret store like vault. https://www.vaultproject.io/

But, the Project now is : https://github.com/ClubCedille/docker-debian-ldap
Since this current project is unmaintened as you can see in readme.

**Comment by mikefaille** [comment]
@ldionmarcil Ici, on recommande d'utiliser des volumes au lieu des variables d'environnements. Le même auteur dit que les variables d'environnements sont possibles mais que ça ne serait pas la meilleure solution. L'idéal serait d'utiliser des volumes : https://github.com/kubernetes/kubernetes/issues/4710#issuecomment-157620716

**Comment by mikefaille** [comment]
@ldionmarcil  When we use env. var. as password injection, I add "immediatly delete cleartext password in memory'" as you can see here : https://github.com/ClubCedille/docker-debian-fusiondirectory/commit/f707b956aa53b5b9789925a3353858979a51a464
